groups = ["1.GRUP",
"2.GRUP",
"3.GRUP"
]

districts = ["Adalar",
"Ataşehir",
"Arnavutköy",
"Avcılar",
"Bağcılar",
"Bahçelievler",
"Bakırköy",
"Başakşehir",
"Bayrampaşa",
"Beşiktaş",
"Beykoz",
"Beylikdüzü",
"Beyoğlu",
"Büyükçekmece",
"Çatalca",
"Çekmeköy",
"Esenler",
"Esenyurt",
"Eyüpsultan",
"Fatih",
"Gaziosmanpaşa",
"Güngören",
"Kadıköy",
"Kağıthane",
"Kartal",
"Küçükçekmece",
"Maltepe",
"Pendik",
"Sancaktepe",
"Sarıyer",
"Silivri",
"Sultanbeyli",
"Sultangazi",
"Şile",
"Şişli",
"Tuzla",
"Ümraniye",
"Üsküdar",
"Zeytinburnu"
]
teams_data = [
    {"name": "KUCUKCEKMECE SPORTIF FAALIYETLERI", "district": "Küçükçekmece", "group": "1.GRUP"},
    {"name": "INKILAP FUTBOL SPOR KULUBU", "district": "Ümraniye", "group": "1.GRUP"},
    {"name": "ISTANBUL ANADOLU FUTBOL YATIRIMLARI", "district": "Maltepe", "group": "1.GRUP"},
    {"name": "BEYKOZ ISHAKLI SPOR FAALIYETLERI", "district": "Beykoz", "group": "1.GRUP"},
    {"name": "ISTANBUL BEYLIKDUZUSPOR", "district": "Beylikdüzü", "group": "1.GRUP"},
    {"name": "YENI UFUKSPOR", "district": "Küçükçekmece", "group": "1.GRUP"},
    {"name": "SARIYER YENIMAHALLESPOR", "district": "Sarıyer", "group": "1.GRUP"},
    {"name": "MALTEPESPOR", "district": "Maltepe", "group": "1.GRUP"},
    {"name": "VEFASPOR", "district": "Fatih", "group": "1.GRUP"},
    {"name": "SILE YILDIZ SPOR", "district": "Şile", "group": "1.GRUP"},
    {"name": "ALIBEYKOYSPOR", "district": "Eyüpsultan", "group": "1.GRUP"},
    {"name": "BAYRAMPASA SPOR", "district": "Bayrampaşa", "group": "1.GRUP"},
    {"name": "NISANTASISPOR", "district": "Şişli", "group": "1.GRUP"},
    {"name": "BEYLERBEYI 1911 FUTBOL KULUBU", "district": "Üsküdar", "group": "1.GRUP"},
    {"name": "KARTAL SPORTIF FAALIYETLERI", "district": "Kartal", "group": "1.GRUP"},
    {"name": "HALIC", "district": "Fatih", "group": "1.GRUP"},
    {"name": "BAGCILARSPOR", "district": "Bağcılar", "group": "2.GRUP"},
    {"name": "BAKIRKOYSPOR", "district": "Bakırköy", "group": "2.GRUP"},
    {"name": "BAHCESEHIRSPOR", "district": "Başakşehir", "group": "2.GRUP"},
    {"name": "ESENYURTSPOR", "district": "Esenyurt", "group": "2.GRUP"},
    {"name": "ESENLERSPOR", "district": "Esenler", "group": "2.GRUP"},
    {"name": "EYUPSULTANSPOR", "district": "Eyüpsultan", "group": "2.GRUP"},
    {"name": "FATIH KARAGUMRUK", "district": "Fatih", "group": "2.GRUP"},
    {"name": "GAZIOSMANPASASPOR", "district": "Gaziosmanpaşa", "group": "2.GRUP"},
    {"name": "GUNGORENSPOR", "district": "Güngören", "group": "2.GRUP"},
    {"name": "KADIKOYSPOR", "district": "Kadıköy", "group": "2.GRUP"},
    {"name": "KARTALSPOR", "district": "Kartal", "group": "2.GRUP"},
    {"name": "ABBASAGASPOR", "district": "Beşiktaş", "group": "2.GRUP"},
    {"name": "FERIKOY", "district": "Şişli", "group": "2.GRUP"},
    {"name": "TAKSIMSPOR", "district": "Beyoğlu", "group": "2.GRUP"},
    {"name": "SARIYERSPOR", "district": "Sarıyer", "group": "2.GRUP"},
    {"name": "SILIVRISPOR", "district": "Silivri", "group": "2.GRUP"},
    {"name": "SULTANBEYLISPOR", "district": "Sultanbeyli", "group": "3.GRUP"},
    {"name": "SISLISPOR", "district": "Şişli", "group": "3.GRUP"},
    {"name": "TUZLASPOR", "district": "Tuzla", "group": "3.GRUP"},
    {"name": "YILDIZSPOR", "district": "Beşiktaş", "group": "3.GRUP"},
    {"name": "ZEYTINBURNUSPOR", "district": "Zeytinburnu", "group": "3.GRUP"},
    {"name": "SERENCEBEYSPOR", "district": "Beşiktaş", "group": "3.GRUP"},
    {"name": "CAFERAĞASPOR", "district": "Kadıköy", "group": "3.GRUP"},
    {"name": "KARACAAHMETSPOR", "district": "Üsküdar", "group": "3.GRUP"},
    {"name": "BEYOĞLUSPOR", "district": "Beyoğlu", "group": "3.GRUP"},
    {"name": "SULTANAHMETSPOR", "district": "Fatih", "group": "3.GRUP"},
    {"name": "EMINONUSPOR", "district": "Fatih", "group": "3.GRUP"},
    {"name": "CIBALISPOR", "district": "Fatih", "group": "3.GRUP"},
    {"name": "KABATASPOR", "district": "Beyoğlu", "group": "3.GRUP"},
    {"name": "YENIKOYSPOR", "district": "Sarıyer", "group": "3.GRUP"},
    {"name": "FLORYASPOR", "district": "Bakırköy", "group": "3.GRUP"},
    {"name": "CADDEBOSTANSPOR", "district": "Kadıköy", "group": "3.GRUP"}
]

venue_data = [
    {"venue_name": "Gulsuyu", "district_name": "Maltepe", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Dudullu", "district_name": "Ümraniye", "available_time_start": "14:30", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Kaynarca", "district_name": "Pendik", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Camlık", "district_name": "Pendik", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Sultanbeyli", "district_name": "Sultanbeyli", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Sarigazi", "district_name": "Sancaktepe", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Kavacik", "district_name": "Beykoz", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Cavusbasi", "district_name": "Beykoz", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Pasabahce", "district_name": "Beykoz", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Beylerbeyi", "district_name": "Üsküdar", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Beykoz", "district_name": "Beykoz", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Ishakli", "district_name": "Beykoz", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Selimiye", "district_name": "Üsküdar", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Yeni Sahra", "district_name": "Ataşehir", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Dolayoba", "district_name": "Pendik", "available_time_start": "12:30", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Basibuyuk", "district_name": "Maltepe", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Bulvar Mimar Kose", "district_name": "Kartal", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Yunus", "district_name": "Kartal", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Kartal 75", "district_name": "Kartal", "available_time_start": "11:15", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Ayazaga Ataturk", "district_name": "Sarıyer", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Kemerburgaz", "district_name": "Eyüpsultan", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Seyrantepe", "district_name": "Kağıthane", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Yahya Kemal", "district_name": "Kağıthane", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Hasbahce", "district_name": "Kağıthane", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Nurtepe", "district_name": "Kağıthane", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Abide Hurreyet", "district_name": "Kağıthane", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Mehmet Akif", "district_name": "Kağıthane", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Alibey", "district_name": "Eyüpsultan", "available_time_start": "12:30", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Parseller", "district_name": "Eyüpsultan", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Karadolap", "district_name": "Eyüpsultan", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Bahariye", "district_name": "Eyüpsultan", "available_time_start": "12:30", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Seyit Ates", "district_name": "Sultangazi", "available_time_start": "11:30", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Necip Uysal", "district_name": "Bayrampaşa", "available_time_start": "11:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "K.C. Metin Oktay", "district_name": "Küçükçekmece", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Guzelce", "district_name": "Büyükçekmece", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "K. Hasan Dogan", "district_name": "Zeytinburnu", "available_time_start": "13:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Mujdat Gursu", "district_name": "Silivri", "available_time_start": "12:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Cebeci", "district_name": "Sultangazi", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Gazi Mah", "district_name": "Sultangazi", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Parseller", "district_name": "Eyüpsultan", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Gokturk", "district_name": "Eyüpsultan", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Esenyurt", "district_name": "Esenyurt", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Ortacesme", "district_name": "Beykoz", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Idealtepe", "district_name": "Maltepe", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "Ümraniye Hekimbasi", "district_name": "Ümraniye", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": False, "accepts_outside_teams": True},
    {"venue_name": "B.Cekmece Bld", "district_name": "Büyükçekmece", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": False},
    {"venue_name": "Arnavutkoy", "district_name": "Arnavutköy", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": False},
    {"venue_name": "Silivri", "district_name": "Silivri", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True},
    {"venue_name": "Kavacik", "district_name": "Beykoz", "available_time_start": "00:00", "available_time_end": "00:00", "venue_availablity": True, "accepts_outside_teams": True}
]
