groups = ["1.GRUP",
"2.GRUP",
"3.GRUP",
"4.GRUP",
"5.GRUP",
"6.GRUP",
"7.GRUP",
"8.GRUP",
"9.GRUP",
"10.GRUP",
]

districts = ["Adalar",
"Ataşehir",
"Arnavutköy",
"Avcılar",
"Bağcılar",
"Bahçelievler",
"Bakırköy",
"Başakşehir",
"Bayrampaşa",
"Beşiktaş",
"Beykoz",
"Beylikdüzü",
"Beyoğlu",
"Büyükçekmece",
"Çatalca",
"Çekmeköy",
"Esenler",
"Esenyurt",
"Eyüpsultan",
"Fatih",
"Gaziosmanpaşa",
"Güngören",
"Kadıköy",
"Kağıthane",
"Kartal",
"Küçükçekmece",
"Maltepe",
"Pendik",
"Sancaktepe",
"Sarıyer",
"Silivri",
"Sultanbeyli",
"Sultangazi",
"Şile",
"Şişli",
"Tuzla",
"Ümraniye",
"Üsküdar",
"Zeytinburnu"
]
venue_data = [
    {"venue_name": "Gulsuyu Sahasi", "district_name": "Maltepe", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Dudullu Sahasi", "district_name": "Ümraniye", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': False, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Kaynarca Sahasi", "district_name": "Pendik", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Camlık Sahasi", "district_name": "Pendik", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Sultanbeyli Sahasi", "district_name": "Sultanbeyli", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Sarigazi Sahasi", "district_name": "Sancaktepe", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Kavacik Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Cavusbasi Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Pasabahce Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Beylerbeyi Sahasi", "district_name": "Üsküdar", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Beykoz Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Ishakli Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Selimiye Sahasi", "district_name": "Üsküdar", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Yeni Sahra Sahasi", "district_name": "Ataşehir", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Dolayoba Sahasi", "district_name": "Pendik", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Basibuyuk Sahasi", "district_name": "Maltepe", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': True, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Bulvar Mimar Kose Sahasi", "district_name": "Kartal", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': True, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Yunus Sahasi", "district_name": "Kartal", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Kartal 75 Sahasi", "district_name": "Kartal", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Ayazaga Ataturk Sahasi", "district_name": "Sarıyer", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Kemerburgaz Sahasi", "district_name": "Eyüpsultan", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Seyrantepe Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Yahya Kemal Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Hasbahce Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Nurtepe Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Abide Hurriyet Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Mehmet Akif Sahasi", "district_name": "Kağıthane", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Alibey Sahasi", "district_name": "Eyüpsultan", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Parseller Sahasi", "district_name": "Eyüpsultan", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Karadolap Sahasi", "district_name": "Eyüpsultan", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Bahariye Sahasi", "district_name": "Eyüpsultan", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Seyit Ates Sahasi", "district_name": "Sultangazi", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Necip Uysal Sahasi", "district_name": "Bayrampaşa", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "K.C. Metin Oktay Sahasi", "district_name": "Küçükçekmece", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Guzelce Sahasi", "district_name": "Büyükçekmece", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "K. Hasan Dogan Sahasi", "district_name": "Zeytinburnu", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Mujdat Gursu Sahasi", "district_name": "Silivri", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Cebeci Sahasi", "district_name": "Sultangazi", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': True, 'slot_two': True, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Gazi Mah Sahasi", "district_name": "Sultangazi", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': True, 'slot_two': True, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Parseller Sahasi", "district_name": "Eyüpsultan", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Gokturk Sahasi", "district_name": "Eyüpsultan", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Esenyurt Sahasi", "district_name": "Esenyurt", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Ortacesme Sahasi", "district_name": "Beykoz", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Idealtepe Sahasi", "district_name": "Maltepe", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Ümraniye Hekimbasi Sahasi", "district_name": "Ümraniye", "venue_availablity": False, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "B.Cekmece Bld Sahasi", "district_name": "Büyükçekmece", "venue_availablity": True, "accepts_outside_teams": False, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Arnavutkoy Sahasi", "district_name": "Arnavutköy", "venue_availablity": True, "accepts_outside_teams": False, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Silivri Sahasi", "district_name": "Silivri", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True},
    {"venue_name": "Kavacik Sahasi", "district_name": "Beykoz", "venue_availablity": True, "accepts_outside_teams": True, 'slot_one': False, 'slot_two': False, 'slot_three': True, 'slot_four': True, 'slot_five': True}
]
